### ISSUE TITLE
Python 2.7.13

### ISSUE THREAD

**Issue by netbauer** [bradh11/cucm-exporter#2]
root@server:/opt/cucm-exporter# python cucm-exporter.py -a 1.1.1.1 -v 11.5 -o "phones.csv" -u user -p pass  -t --export phones
  File "cucm-exporter.py", line 18
    print(f"status: starting {start_time}")
                                         ^
SyntaxError: invalid syntax

**Comment by bradh11** [comment]
This app is only supported under Python 3.7 or later.  You may however use the bundle executables in the releases.  I will update the readme to make sure the Python 3.7 requirement is noted.  Thank you for the feedback.
